# Generated by Django 4.2.28 on 2026-03-01 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Voting'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voting_election',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Short identifier (e.g. "C01")', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.election')),
            ],
            options={
                'db_table': 'voting_candidate',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ref', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ballot_code', models.CharField(help_text='Unique ballot identifier printed on the paper ballot.', max_length=50)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='voting.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='voting.election')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots_entered', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ballots_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voting_ballot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VERIFY', 'Verified'), ('REJECT', 'Rejected'), ('BULK_IMPORT', 'Bulk Imported')], db_index=True, max_length=15)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ballot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='voting.ballot')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='voting.election')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voting_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('verified_votes', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_summary', to='voting.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_summaries', to='voting.election')),
            ],
            options={
                'db_table': 'voting_vote_summary',
                'indexes': [models.Index(fields=['election', 'total_votes'], name='idx_vsummary_election_total')],
                'unique_together': {('election', 'candidate')},
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'code'], name='idx_candidate_election_code'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'code')},
        ),
        migrations.AddIndex(
            model_name='ballot',
            index=models.Index(fields=['election', 'candidate'], name='idx_ballot_election_cand'),
        ),
        migrations.AddIndex(
            model_name='ballot',
            index=models.Index(fields=['election', 'verification_status'], name='idx_ballot_election_vstatus'),
        ),
        migrations.AddIndex(
            model_name='ballot',
            index=models.Index(fields=['entered_by'], name='idx_ballot_entered_by'),
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('election', 'ballot_code')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['election', 'action'], name='idx_audit_election_action'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['performed_by', 'timestamp'], name='idx_audit_user_ts'),
        ),
    ]
