# Generated by Django 4.2.28 on 2026-03-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='voting.candidate'),
        ),
        migrations.CreateModel(
            name='BallotChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='voting.ballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballot_choices', to='voting.candidate')),
            ],
            options={
                'db_table': 'voting_ballot_choice',
                'unique_together': {('ballot', 'candidate')},
            },
        ),
    ]
