# Generated by Django 4.2.29 on 2026-03-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_candidate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='is_invalid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='max_choices',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of choices allowed for a valid ballot', null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='min_choices',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of choices required for a valid ballot', null=True),
        ),
    ]
